name: flutwalls
description: Simple Flutter App showing trending images from Unsplash (https://unsplash.com/).
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter

  # display images in staggered grid
  flutter_staggered_grid_view: ^0.3.0
  # open url for an image
  url_launcher: ^5.4.1
  # image loading
  cached_network_image: ^2.0.0
  # zoom images
  photo_view: ^0.9.0
  # format date
  date_format: ^1.0.8
  # image provider
  flutter_image: ^3.0.0
  # download image
  image_downloader: ^0.19.1
  # set wallpaper
  wallpaper: ^1.0.0
  # flare
  flare_flutter: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # launcher icons
  flutter_launcher_icons: "^0.7.4"

# specify launcher icons
flutter_icons:
  image_path_android: "assets/ic_launcher_android.png"
  android: true # can specify file name here e.g. "ic_launcher"
  image_path_ios: "assets/ic_launcher_ios.png"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # android adaptive icons only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/ic_launcher_foreground.png"
  adaptive_icon_background: "assets/ic_launcher_background.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Loading indicator.flr
